(** Return the search Rectangle encloseing the Vaccine Column of Immunization History Table
@return - coordinates of the SearchRectangle
@Handler
     "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/ImmunizationHistory/Helpers".immunizationHistoryVaccineColumnSearchRectangle()
**)
function immunizationHistoryVaccineColumnSearchRectangle
	set immunizationHistoryContentRectangle to "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/Helpers".tableContentSearchRectangle("Immunization History")
	
	set topLeft to immunizationHistoryContentRectangle.topLeft
	set bottomRight to ((immunizationHistoryContentRectangle.left + (immunizationHistoryContentRectangle.width / 5)) + 7, immunizationHistoryContentRectangle.bottom)
	
	return (topLeft, bottomRight)
end immunizationHistoryVaccineColumnSearchRectangle

(** Return the search Rectangle encloseing the Dose Column of Immunization History Table
@return - coordinates of the SearchRectangle
@Handler
     "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/ImmunizationHistory/Helpers".immunizationHistoryDoseColumnSearchRectangle()
**)
function immunizationHistoryDoseColumnSearchRectangle
	set immunizationHistoryContentRectangle to "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/Helpers".tableContentSearchRectangle("Immunization History")
	
	set topLeft to immunizationHistoryContentRectangle.topLeft + ((immunizationHistoryContentRectangle.width / 5) + 7, 0)
	set bottomRight to ((immunizationHistoryContentRectangle.left + (immunizationHistoryContentRectangle.width / 5) * 2) + 7, immunizationHistoryContentRectangle.bottom)
	
	return (topLeft, bottomRight)
end immunizationHistoryDoseColumnSearchRectangle

(** Return the search Rectangle encloseing the Status Column of Immunization History Table
@return - coordinates of the SearchRectangle
@Handler
     "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/ImmunizationHistory/Helpers".immunizationHistoryStatusColumnSearchRectangle()
**)
function immunizationHistoryStatusColumnSearchRectangle
	set immunizationHistoryContentRectangle to "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/Helpers".tableContentSearchRectangle("Immunization History")
	
	set topLeft to immunizationHistoryContentRectangle.topLeft + ((immunizationHistoryContentRectangle.width / 5)*2 + 7, 0)
	set bottomRight to ((immunizationHistoryContentRectangle.left + (immunizationHistoryContentRectangle.width / 5) * 3), immunizationHistoryContentRectangle.bottom)
	
	return (topLeft, bottomRight)
end immunizationHistoryStatusColumnSearchRectangle

(** Return the search Rectangle encloseing the Valid Dose Column of Immunization History Table
@return - coordinates of the SearchRectangle
@Handler
     "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/ImmunizationHistory/Helpers".immunizationHistoryValidDoseColumnSearchRectangle()
**)
function immunizationHistoryValidDoseColumnSearchRectangle
	set immunizationHistoryContentRectangle to "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/Helpers".tableContentSearchRectangle("Immunization History")
	
	set topLeft to immunizationHistoryContentRectangle.topLeft + ((immunizationHistoryContentRectangle.width / 5)*3, 0)
	set bottomRight to ((immunizationHistoryContentRectangle.left + (immunizationHistoryContentRectangle.width / 5) * 4) - 3, immunizationHistoryContentRectangle.bottom)
	
	return (topLeft, bottomRight)
end immunizationHistoryValidDoseColumnSearchRectangle

(** Return the search Rectangle encloseing the Admin Date Column of Immunization History Table
@return - coordinates of the SearchRectangle
@Handler
     "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/ImmunizationHistory/Helpers".immunizationHistoryAdminDateColumnSearchRectangle()
**)
function immunizationHistoryAdminDateColumnSearchRectangle
	set immunizationHistoryContentRectangle to "Immunizations/WorkflowMPage/Reconciliation/RegistryForecast/Tables/Helpers".tableContentSearchRectangle("Immunization History")
	
	set topLeft to immunizationHistoryContentRectangle.topLeft + ((immunizationHistoryContentRectangle.width / 5)*4 - 3, 0)
	set bottomRight to ((immunizationHistoryContentRectangle.left + (immunizationHistoryContentRectangle.width / 5) * 5) - 3, immunizationHistoryContentRectangle.bottom)
	
	return (topLeft, bottomRight)
end immunizationHistoryAdminDateColumnSearchRectangle
